### ISSUE TITLE
Start de projetos no visual studio

### ISSUE THREAD

**Issue by adrianogodoy** [puc-aswd-web/trabalho-final#4]
Descobrir como configurar para que, ao startar no visual studio um projeto (marcado como StartUp Project), outro projeto também seja iniciado (em uma outra porta específica).

Assim poderíamos iniciar apenas o projeto de apresentação Web (html/css) e o projeto Web.api seria automaticamente executado em outra porta.

**Comment by lucasteles22** [comment]
Pelo que vi aqui, cada um deverá configurar no visual studio. Segue o link abaixo:
https://msdn.microsoft.com/en-us/library/ms165413.aspx

Um exemplo visual da configuração:
http://stackoverflow.com/questions/19924393/vs2012-multiple-startup-projects#answer-19924455

A configuração fica a cargo de cada um. Geralmente configuro para "start without debug" para ir mais rápido. Se precisar de utilizar break point ou analisar o stack trace, eu mudo apenas para start.

**Comment by adrianogodoy** [comment]
É verdade.. o ideal era que esse setup ficasse configurado no arquivo .sln, .suo ou .csproj, assim ficava mais simples passar as instruções para o Marco executar o projeto para avaliar. Pena ser no visual studio.
