### ISSUE TITLE
Configurar JS com angular 

### ISSUE THREAD

**Issue by adrianogodoy** [puc-aswd-web/trabalho-final#5]
Instalar Angular pelo bower e configurar uma task para montar um Javascript juntando as dependencias (angular, jquery, ...) com os scripts feitos na aplicação em um único script a ser incluído no HTML.

**Comment by ismaelsoj** [comment]
Estou estudando o Angular e pretendo iniciar um projeto durante o fim de semana

**Comment by adrianogodoy** [comment]
Beleza! Hoje a noite vou só incluir o angular no projeto e configurar o gulp para minificar todos os scripts. Também tenho que estudar melhor o angular antes de colocar a mão na massa.

**Comment by adrianogodoy** [comment]
O @lucasteles22  já começou a se divertir nas férias: https://github.com/lucasteles22/mvc6-angularjs-mongodb
Fez o trabalho todo em paralelo no asp.net mvc6 :)
haha

**Comment by lucasteles22** [comment]
Só lembrando que esse projeto eu usei o novo Asp.net 5 com .NET core, cross plataform.
Sendo assim, desenvolvi no MAC.

**Comment by adrianogodoy** [comment]
Blza. Vamos continuar nesse projeto aqui, com a pilha tecnológica que já havíamos discutido em sala
