### ISSUE TITLE
Configurar Model (classes e tabelas)

### ISSUE THREAD

**Issue by lucasteles22** [puc-aswd-web/trabalho-final#7]
Configurar a camada de Model no projeto de acordo com o template discutido em sala.

![atkj60zmmriorcotuy4evxny1spxzp2jhzqdm5c4fmzm](https://cloud.githubusercontent.com/assets/4269000/8864622/74b223be-317a-11e5-981c-b1cf3392d43e.jpg)

**Comment by adrianogodoy** [comment]
Passei a limpo para o trabalho da aula 05: 
(o fonte do astah está compartilhado no google drive naquela pasta de disciplina. Se for necessário alterar atualizem lá por favor)

![diagramaclasses](https://cloud.githubusercontent.com/assets/1420198/8864665/0b7d4cf6-317b-11e5-9da9-bbd7d44cb89d.jpg)

**Comment by lucasteles22** [comment]
Preciso que listem as propriedades das tabelas para commitar.
Já fiz todos os relacionamentos.

Exemplo:
Disciplina -> Id, Nome.
Nota -> Id, Valor,
Turma -> Id, Nome
.....

**Comment by adrianogodoy** [comment]
Vamos pensar no mínimo pra fazer o que foi pedido no trabalho:

1- Um aluno deseja consultar as suas notas, por disciplina ou intervalo de períodos.
2- Um coordenador deseja consultar as notas dos alunos do seu curso, por disciplina ou intervalo de períodos.
3- Uma secretária do diretório acadêmico deseja consultar a nota de qualquer aluno, de um curso qualquer, mediante uma requisição de um aluno.

Já vi que faltou criar uma classe Curso e relacionar com DisciplinaPeriodo e com Coordenador, pra atender o item 2.

**Comment by lucasteles22** [comment]
1- Um aluno deseja consultar as suas notas, por disciplina ou intervalo de períodos.
Disciplina: Nome. DisciplinaPeriodo: Data início, data fim.

2- Um coordenador deseja consultar as notas dos alunos do seu curso, por disciplina ou intervalo de períodos.
Curso: Criar tabela com campo nome.

3- Uma secretária do diretório acadêmico deseja consultar a nota de qualquer aluno, de um curso qualquer, mediante uma requisição de um aluno.
-

**Comment by adrianogodoy** [comment]
Atualizando..
![diagramaclasses](https://cloud.githubusercontent.com/assets/1420198/8880476/78ef3e90-320f-11e5-88c9-78c14303d77c.jpg)

**Comment by lucasteles22** [comment]
Finalizado
