### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by adrianogodoy** [puc-aswd-web/trabalho-final#9]
Criar login
- Interface (html/css) com campos matricula e senha
- Login no angular
- Login no ASP.NET (acho que o @lucasteles22 já deixou no jeito a autenticação na web api - inclusive com geração de token)

**Comment by adrianogodoy** [comment]
@lucasteles22  fechou isso, certo?

**Comment by jefferson** [comment]
Falta criar uma rota no AccountController para autenticação certo?
Vi que esta rolando um post em um /token para a autenticação, o que estão pensando em fazer?

**Comment by lucasteles22** [comment]
@adrianogodoy Fechado.

@jefferson Não entendi? A autenticação eh via token e  já está funcionando.

**Comment by jefferson** [comment]
Humm, não consegui autenticar com os usuários que estão no seed.
Vou verificar se estou com o último branch.

**Comment by jefferson** [comment]
O ambiente esta ok, esta com a última versão.
![git log](https://cloud.githubusercontent.com/assets/1058753/9156784/38eb4514-3ebc-11e5-8e9c-2b16de702043.PNG)

Sempre que executo a autenticação o método sempre retorna usuários nulos:
GrantResourceOwnerCredentials

**Comment by lucasteles22** [comment]
Para mim aqui ta normal!
![Uploading Screen Shot 2015-08-09 at 20.28.18.png…]()

Olhe se está passando os parâmetros certos.
![screen shot 2015-08-09 at 20 28 29](https://cloud.githubusercontent.com/assets/4269000/9157477/6eb16fac-3ed5-11e5-947c-456da5468cf7.png)

**Comment by lucasteles22** [comment]
Primeira imagem:
![screen shot 2015-08-09 at 20 28 18](https://cloud.githubusercontent.com/assets/4269000/9157478/7fd5bec8-3ed5-11e5-84bc-c2cbc1597d2c.png)

**Comment by jefferson** [comment]
Estava testando e acho que o banco de dados veio com os dados, e talvez por algum o hash no banco de dados não esta conseguindo checar as senhas adequadamente.

Alterei para verificar apenas por e-mail e rodou. Vou apagar os dados e rodar o seed de novo para ver o resultado.

**Comment by lucasteles22** [comment]
Finalizado
